// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLY_FvtVr3U8-oQUDrc0vAS5VMQul70iE',
    appId: '1:281086640871:web:1cdbf950da2a8c21ab9842',
    messagingSenderId: '281086640871',
    projectId: 'sambat-yuk',
    authDomain: 'sambat-yuk.firebaseapp.com',
    databaseURL: 'https://sambat-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sambat-yuk.appspot.com',
    measurementId: 'G-P089L8CM8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBLxXBuPluIcOM8zauygZqavhvGfWSQQ',
    appId: '1:281086640871:android:50c9c11a74ecb196ab9842',
    messagingSenderId: '281086640871',
    projectId: 'sambat-yuk',
    databaseURL: 'https://sambat-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sambat-yuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSTehv3uJ6aDLLPDbKL9w_2VTEdHUCNVo',
    appId: '1:281086640871:ios:32c22d5deccf0283ab9842',
    messagingSenderId: '281086640871',
    projectId: 'sambat-yuk',
    databaseURL: 'https://sambat-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sambat-yuk.appspot.com',
    iosClientId: '281086640871-90768nu6llron44tl74d7ehkhmab44fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipalingSirkel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSTehv3uJ6aDLLPDbKL9w_2VTEdHUCNVo',
    appId: '1:281086640871:ios:32c22d5deccf0283ab9842',
    messagingSenderId: '281086640871',
    projectId: 'sambat-yuk',
    databaseURL: 'https://sambat-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sambat-yuk.appspot.com',
    iosClientId: '281086640871-90768nu6llron44tl74d7ehkhmab44fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipalingSirkel',
  );
}
